### ISSUE TITLE
feature request: builds for aarch64

### ISSUE THREAD

**Issue by theodiem** [mcronce/oci-registry#1]
Hello,

I've came across your project from a reddit post. Nice work, many thanks.
It is just a pity that there's only x86-64 builds, so I cannot run oci-registry in a raspberry pi cluster (aarch64 , I believe target for rust is armv7-unknown-linux-gnueabihf, but I'm no expert).

Many thanks for publishing this and I'm looking forward for the feature to avoid duplication of upstream streams when fetching the same layer in parallel.

**Comment by mcronce** [comment]
I'll look into getting multiarch images going w/ aarch64 support.  I expect it won't be too tough.

**Comment by mcronce** [comment]
@theodiem I don't have any ARM devices to test on currently (my Pi is apparently offline :disappointed: ) but in theory, `mcronce/oci-registry:v0.3.7` is now a multi-arch image with both x86-64 and aarch64 variants.  Do you mind pulling it on one of your Pis to see if it works?

**Comment by zargony** [comment]
I didn't create this issue, but I just tried on my MacBook M1 (with --platform linux/arm64 to disable amd64 emulation in containers) and it works fine. Also [Docker Hub](https://hub.docker.com/r/mcronce/oci-registry/tags) shows v0.3.7 as multiarch now. Thanks a lot!

**Comment by theodiem** [comment]
> @theodiem I don't have any ARM devices to test on currently (my Pi is apparently offline 😞 ) but in theory, `mcronce/oci-registry:v0.3.7` is now a multi-arch image with both x86-64 and aarch64 variants. Do you mind pulling it on one of your Pis to see if it works?

@mcronce I was testing it (configuring it properly, not just executing it). It works fine for me, using the multiarch manifest. I did not need to pass --platform when running natively (as expected).

Just one thing, you might mention to test the containerd configuration you can do it with: ` ctr --debug images pull --hosts-dir "/etc/containerd/certs.d" docker.io/library/alpine:latest` .
Since depending on the cli it is used, the configuration might not be loaded (and then it is neither your/containerd fault - looking at you podman)

**Comment by mcronce** [comment]
TIL you can use `ctr images pull` with `--hosts-dir` :)

Cool, I'll commit the changes.  Cheers!

**Comment by mcronce** [comment]
Everything's committed/pushed up.  Currently the aarch64 image is larger (based on `debian` instead of `distroless/cc-debian`), and doesn't have any PGO/BOLT applied to the binary - but it should all be working, and the next version that's pushed should automatically get a multiarch image built for it
