### ISSUE TITLE
Cannot pull some images from docker hub

### ISSUE THREAD

**Issue by theodiem** [mcronce/oci-registry#5]
Hello,
I've been using oci-registry quite happily but I've found one issue which I have not much clue where to start checking.
I have my environment configured, hopefully correctly, so when I do a `podman pull docker.io/mcronce/oci-registry:v0.3.11` or  `podman pull docker.io/alpine:latest`, I can confirm that oci-registry is being used as I see their manifest and blobs on oci-registry storage folder.

But for example it doesn't work for `docker.io/syncthing/syncthing:1.23`.
I get the following in the logs:
```
2023-07-13T02:32:16.803904Z  INFO actix_web::middleware::logger: 10.192.1.167 "GET /v2/ HTTP/1.1" 200 0 "-" "containers/5.19.1 (github.com/containers/image)" 0.872745
2023-07-13T02:32:16.998518Z  WARN oci_registry::api: /syncthing/syncthing/manifests/1.23 not found at manifests/docker.io/syncthing/syncthing/1.23 in repository (I/O error: No such file or directory (os error 2)); pulling from upstream
2023-07-13T02:32:17.401124Z ERROR oci_registry::api::error: 500: Error with upstream registry: unexpected HTTP status 404 Not Found
2023-07-13T02:32:17.401804Z  INFO actix_web::middleware::logger: 10.192.1.167 "GET /v2/syncthing/syncthing/manifests/1.23 HTTP/1.1" 500 66 "-" "containers/5.19.1 (github.com/containers/image)" 0.403822
```
But works when not using oci-registry as mirror (my current config actually falls back to `registry-1.docker.io` when there's an issue with a mirror, so the command actually pulls the image, but oci-registry cannot).

for example:
```
podman run --rm mplatform/mquery docker.io/syncthing/syncthing:1.23
Image: docker.io/syncthing/syncthing:1.23 (digest: sha256:88d6c8516d27876f6dacf7b9b544075d70e0d42480a2e85ec4dbb313764cc1e6)
 * Manifest List: Yes (Image type: application/vnd.oci.image.index.v1+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm64
   - unknown/unknown
   - unknown/unknown
```

**Comment by theodiem** [comment]
Just noticed that all other images I did try (and worked) have type `application/vnd.docker.distribution.manifest.list.v2+json` , whereas `docker.io/syncthing/syncthing:1.23` is ` application/vnd.oci.image.index.v1+json`.

Is there any filter/different processing (or maybe not implemented) for that type?

**Comment by theodiem** [comment]
Maybe some additional light....
While I was writing some regex rules in traefik (which i configured in front of oci-registry), so I could forcefully "support" the `?ns={namespace}` query ...  I've noticed other manifests failing.
For example:
- works : `curl "https://gcr.io/v2/kaniko-project/executor/manifests/v1.9.1-debug"`
- doesn't work: `curl "https://oci-registry:8080/v2/kaniko-project/executor/manifests/v1.9.1-debug?ns=gcr.io"`
Maybe because: `curl "https://gcr.io/v2/kaniko-project/executor/manifests/v1.9.1-debug?ns=gcr.io"` also returns a 404? ....

So .. I'm not so familiar with rust, but .. are you removing the `ns` query string before forwarding upstream?

**Comment by theodiem** [comment]
Seems I have found something ... 
Disabling TLS from upstream.yaml enabled me to sniff out the requests.
```
GET /v2/kaniko-project/executor/manifests/v1.9.1-debug?ns=gcr.io HTTP/1.1
....

HTTP/1.1 301 Moved Permanently
Location: https://gcr.io/v2/kaniko-project/executor/manifests/v1.9.1-debug?ns=gcr.io
```

So I would recommend removing the ns query parameter from the URI before accessing upstream. It seems some servers out there don't like it.

Now if that would fix my original problem is a different thing ...

**Comment by theodiem** [comment]
I promise, last comment for today.
It seems in case of `docker.io/syncthing/syncthing:latest`, it send actually an "401 Unauthorized".
It requires to get a token from `https://auth.docker.io/token` :
```
< HTTP/1.1 401 Unauthorized
< content-type: application/json
< docker-distribution-api-version: registry/2.0
< www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io",scope="repository:syncthing/syncthing:pull"
< date: Thu, 13 Jul 2023 20:41:49 GMT
< content-length: 162
< strict-transport-security: max-age=31536000
< docker-ratelimit-source: 192.168.1.1 (i've modified it, it shows my external IP)
```

The process is described in https://docs.docker.com/registry/spec/auth/token/
So I can confirm the original issue is that when oci-registry gets a 401 from docker namespace, it needs to request a bearer token and retry the operation with it. After it the pull works.

I will create a second issue regarding removing the `ns` query string from the URI.

**Comment by mcronce** [comment]
I'll address the `gcr.io` problem in #6 and keep this one for specifically the original problem :)

Your hypothesis that we're not handling certain manifest formats correctly (well, `s/correctly/at all`) is accurate.  This is an unresolved issue from day one that I've just been deferring due to lack of time - it impacts few enough recent images that it hasn't been a high priority.  `docker.io/syncthing/syncthing:1.23` isn't the only thing impacted; I couple in testdata/requests.txt, `docker.io/stedolan/jq:latest` is one example.

I'll see about getting a fix going this/next weekend as I have time.

**Comment by theodiem** [comment]
Looking on the output of `ctr` and comparing with information from tcpdump, I wonder if the issue is not caused by the lack of bearer token. Maybe docker hub requires a token (which includes your IP address among the data) to control the usage quota for certain projects, while others like docker.io/library/alpine (or others with different account type) don't get rate-limited?

Because even ~containerd~ `ctr` without oci-registry gets a `401 Unauthorized` and then requests a bearer token.

Also many thanks for making this piece of software great. Has been really useful for me (running from a rpi).

**Comment by mcronce** [comment]
https://github.com/mcronce/dkregistry-rs/commit/2ff9ff56d4f9d79c1791730965713b70d371b105 + https://github.com/mcronce/dkregistry-rs/commit/228e686d39f65d5d7dbaeb141b8fb6af289e498e fix this

I definitely need to submit all my changes to that project upstream eventually, but for now at least this gets us going on that image type

**Comment by mcronce** [comment]
@theodiem v0.3.12 images and chart are released with these fixes

**Comment by theodiem** [comment]
@mcronce I can confirm it works for me on containerd.

Still I have an issue that it doesn't work with podman (which actually now its "worse" since it gets a HTTP 200 for `/v2/syncthing/syncthing/manifests/1.23.6` but then fails for `/syncthing/syncthing/manifests/sha256:e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c`, the fallback configuration to upstream is not used and it fails pulling entirely.
Output from podman:
```
# podman pull docker.io/syncthing/syncthing:1.23.6
Trying to pull docker.io/syncthing/syncthing:1.23.6...
Error: determining manifest MIME type for docker://syncthing/syncthing:1.23.6: reading manifest sha256:e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c in oci-registry.lan:8080/syncthing/syncthing: received unexpected HTTP status: 500 Internal Server Error
```

Logs from oci-registry:
```
2023-07-16T07:52:27.041539Z  INFO actix_web::middleware::logger: 10.192.1.167 "GET /v2/ HTTP/1.1" 200 0 "-" "containers/5.19.1 (github.com/containers/image)" 0.893090
2023-07-16T07:52:27.215122Z  WARN oci_registry::api: /syncthing/syncthing/manifests/1.23.6 not found at manifests/docker.io/syncthing/syncthing/1.23.6 in repository (I/O error: No such file or directory (os error 2)); pulling from upstream
2023-07-16T07:52:27.654255Z  INFO actix_web::middleware::logger: 10.192.1.167 "GET /v2/syncthing/syncthing/manifests/1.23.6 HTTP/1.1" 200 1609 "-" "containers/5.19.1 (github.com/containers/image)" 0.439666
2023-07-16T07:52:27.824751Z  WARN oci_registry::api: /syncthing/syncthing/manifests/sha256:e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c not found at manifests/docker.io/syncthing/syncthing/sha256:e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c in repository (I/O error: No such file or directory (os error 2)); pulling from upstream
2023-07-16T07:52:28.339415Z ERROR oci_registry::api::error: 500: Error with upstream registry: unexpected HTTP status 404 Not Found
2023-07-16T07:52:28.340039Z  INFO actix_web::middleware::logger: 10.192.1.167 "GET /v2/syncthing/syncthing/manifests/sha256:e84a00b83684b0d75b58ddc1ac5a5265629bcb07d28a7fd9b3874be00cc6279c HTTP/1.1" 500 66 "-" "containers/5.19.1 (github.com/containers/image)" 0.515958
```
It seems oci-registry is not storing the manifest file with its hash and also none of the blobs (no idea if its the root cause, its just an observation) -- either attempting to pull with podman or ctr:
```
./cache/manifests/docker.io/library/debian/latest
./cache/manifests/docker.io/library/debian/sha256:60774985572749dc3c39147d43089d53e7ce17b844eebcf619d84467160217ab
./cache/manifests/docker.io/containous/whoami/latest
./cache/manifests/docker.io/containous/whoami/sha256:7d6a3c8f91470a23ef380320609ee6e69ac68d20bc804f3a1c6065fb56cfa34e
./cache/manifests/docker.io/containous/whoami/sha256:e6d0a6d995c167bd339fa8b9bb2f585acd9a6e505a6b3fb6afb5fcbd52bbefb8
./cache/manifests/docker.io/syncthing/syncthing/latest
./cache/manifests/docker.io/syncthing/syncthing/1.23.6
./cache/manifests/docker.io/rancher/klipper-helm/v0.7.4-build20221121
./cache/manifests/docker.io/rancher/klipper-helm/v0.6.6-build20211022
./cache/manifests/docker.io/rancher/klipper-helm/sha256:0fa01dbbb61412742bbf4fb8ebee2167ea4658796f372f01b604c9aca7c9381f
./cache/manifests/docker.io/rancher/klipper-helm/sha256:961459b8641aa77dae39c96ba8efba88805a8949dcaafa131d1aecc1510128bf
./cache/manifests/docker.io/rancher/klipper-helm/sha256:7d846df48eb8878b66b748bf8fcb322ba778f70e9eedd09c57f8617c544eb056
./cache/manifests/docker.io/rancher/klipper-helm/sha256:f6f9cf9956014af86afe6c8f78cb3444f9c638931d477dfaa4d6a1a49a590a48
```

Btw, if you tell me its a bug with how podman handles mirrors in this condition, I'm fine with creating an issue with podman project. I'm just not familiar enough with the internals of registry to be able to tell.

**Comment by mcronce** [comment]
I'm inclined to assume it's an issue with `oci-registry` until proven otherwise :)

I didn't test this iteration with `podman` - I was able to reproduce everything up until now with `containerd`.  Let me take another look.

**Comment by mcronce** [comment]
Correction - I tested pulling the manifest with `curl`, not pulling the image.  The same thing does indeed happen with `containerd`.  My money right now is on requiring additional handling for `application/vnd.oci.image.index.v1+json` images; https://github.com/mcronce/dkregistry-rs/commit/93e8da98a70d3ea40e891ebe7e866428ec27abbf only added it to the `Accept` header and my test was too narrow

**Comment by mcronce** [comment]
It looks like I just jumped the gun in thinking that adding `application/vnd.oci.image.index.v1+json` to the default `Accept` header was a sufficient fix; `application/vnd.oci.image.manifest.v1+json` was also required.

This whole thing should definitely be reworked so that only specific `Accept` headers are included at appropriate times, but for the time being at least this at least gets us going.

**Comment by mcronce** [comment]
@theodiem I don't have a concrete explanation for why your blobs aren't being saved but I have a couple loose hypotheses

- I'm obligated to ask as a sanity check:  Have you only looked in `/cache/manifests`?  Blobs will be in `/cache/blobs`
- When they see a failure getting the manifest from `oci-registry`,
  - `podman` is giving up on the pull - it doesn't go directly to upstream for the manifest, so it doesn't attempt to pull blobs.  This seems likely based on what you've told me.
  - `containerd` is going straight to upstream for blobs, bypassing `oci-registry`.  I have a harder time with this explanation, because it doesn't match the behavior I observe with my own `containerd`; it's possible that behavior has changed with a more recent version, but that doesn't seem _that_ likely

Either way, I would try v0.3.13 (images are building now) and see if it solves that issue as well.  If not, we can dig in farther.

**Comment by mcronce** [comment]
@theodiem v0.3.13 is up, when you have a moment to try it out let me know how well it works/doesn't work!

**Comment by theodiem** [comment]
@mcronce : So you fixed heh

I just tested v0.3.13 and now it is working for me. It saves the blobs and manifests of `docker.io/syncthing/syncthing:1.23.6` in the cache directory and both podman and containerd (`ctr`) can download the images from it. Many thanks.

More details:
>  Have you only looked in /cache/manifests? Blobs will be in /cache/blobs

No worries, no offence taken here. But yeah .. I was doing a `find ./cache -type f` , so yeah, I was looking for the blobs in the blobs folder.
But also the version v0.3.12 did only saved the manifest "file" but not the file inside the manifest folder with the digest (for example: `./cache/manifests/docker.io/syncthing/syncthing/sha256:bc4fe10f062b00ca132a57b7bf646f83f6da5aafa86d6db8919c1e48258634c7`) . The version v0.3.12 also did not saved any of the files that should have gone to `./cache/blobs/...`).

Maybe it helps out on your testing, my setup (with the "fallback"):
- for containerd:
```
# cat /etc/containerd/certs.d/docker.io/hosts.toml
server = "https://docker.io"

[host."https://oci-registry.lan:8080"]
capabilities = ['pull', 'resolve']
[host."https://registry-1.docker.io"]
```
- for podman (with fallback):
```
# cat /etc/containers/registries.conf
[[registry]]
prefix = "docker.io"
insecure = false
location = "registry-1.docker.io"

[[registry.mirror]]
location = "oci-registry.lan:8080"
insecure = false
```

The thing is that podman (at least 4.0.3-dev) doesn't seems to add the `ns` param to the URI, so I did all the tests with only docker.io (so it is the default upstream on oci-registry) and that now worked on v0.3.13.

In the final deployment here, what I ended up doing for myself is putting a traefik instance in front of oci-registry which does a very ugly rewriting of the URL so I can use `https://oci-registry.traefik.lan/mirror/docker.io/(...)` which gets rewritten to  `https://oci-registry.traefik.lan/${1}?ns=docker.io` . It is awful, I know .. but works. But as I've mentioned, all the tests I did were without this hack to avoid adding more complexity (but mentioning it here so you are aware that, to my experience, seems that podman doesn't send the namespace param).
